# 워크플로우 이름
name: 일일 뉴스 업데이트 (Daily News Update)

# 워크플로우 트리거 조건
on:
  schedule:
    # 매일 자정 UTC (한국 시간 오전 9시)에 실행
    - cron: '0 0 * * *'
  workflow_dispatch: # GitHub UI에서 수동으로 워크플로우 실행 가능

# <<<<<<<<<<<<<<<<<<<<<<<< 핵심: contents: write 필수!
permissions:
  contents: write

jobs:
  update_news_job:
    runs-on: ubuntu-latest

    steps:
      # 1단계: 리포지토리 코드 체크아웃
      - name: 코드 체크아웃 (Checkout repository)
        uses: actions/checkout@v4

      # 2단계: Python 환경 설정
      - name: Python 환경 설정 (Set up Python environment)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3단계: Python 의존성 설치
      - name: 의존성 설치 (Install dependencies)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4단계: 뉴스 업데이트 Python 스크립트 실행
      - name: 뉴스 업데이트 스크립트 실행 (Run news updater script)
        env:
          TRANSLATION_API_KEY: ${{ secrets.TRANSLATION_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY_IF_NEEDED }}
        run: python scripts/news_updater.py

      # 5단계: 변경된 파일 커밋 및 푸시
      - name: 변경사항 커밋 및 푸시 (Commit and push changes)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated daily news update'
          branch: main
          # token 인자 생략 (v5에서는 자동으로 GITHUB_TOKEN 사용)

